<!doctype html>
<html lang="pt-BR">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>Não comece a sessão do zero: Codebase Memory MCP — woss.tech</title>
<meta name="description" content="Quatro perguntas sobre um código que o agente não conhece, medidas nas duas rotas: 8 kB pelo grafo, 680 kB lendo arquivo. E uma que o grep não responde.">
<link rel="canonical" href="https://woss.tech/publicacoes/2026-09-10-nao-comece-a-sessao-do-zero.html">

<meta name="author" content="Anderson Woss">
<meta name="color-scheme" content="light dark">
<meta name="theme-color" content="#f5f4f1" media="(prefers-color-scheme: light)">
<meta name="theme-color" content="#0b0b0a" media="(prefers-color-scheme: dark)">

<meta property="og:type" content="article">
<meta property="og:site_name" content="woss.tech">
<meta property="og:locale" content="pt_BR">
<meta property="og:title" content="Não comece a sessão do zero: Codebase Memory MCP">
<meta property="og:description" content="Quatro perguntas sobre um código que o agente não conhece, medidas nas duas rotas: 8 kB pelo grafo, 680 kB lendo arquivo. E uma que o grep não responde.">
<meta property="og:url" content="https://woss.tech/publicacoes/2026-09-10-nao-comece-a-sessao-do-zero.html">
<meta property="og:image" content="https://woss.tech/assets/og/2026-09-10-nao-comece-a-sessao-do-zero.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="Não comece a sessão do zero: Codebase Memory MCP — woss.tech">
<meta property="article:published_time" content="2026-09-10">
<meta property="article:section" content="Ferramentas">
<meta property="article:author" content="Anderson Woss">
<meta property="article:tag" content="MCP">
<meta property="article:tag" content="agentes">
<meta property="article:tag" content="grafo de código">

<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="Não comece a sessão do zero: Codebase Memory MCP">
<meta name="twitter:description" content="Quatro perguntas sobre um código que o agente não conhece: 8 kB pelo grafo, 680 kB lendo arquivo.">
<meta name="twitter:image" content="https://woss.tech/assets/og/2026-09-10-nao-comece-a-sessao-do-zero.png">
<meta name="twitter:label1" content="Tempo de leitura">
<meta name="twitter:data1" content="8 min">

<link rel="icon" href="/assets/favicon.svg" type="image/svg+xml">
<link rel="icon" href="/assets/favicon-32.png" sizes="32x32" type="image/png">
<link rel="apple-touch-icon" href="/assets/apple-touch-icon.png">
<link rel="manifest" href="/manifest.webmanifest">
<link rel="alternate" type="application/rss+xml" title="woss.tech" href="/feed.xml">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Instrument+Serif:ital@0;1&family=JetBrains+Mono:wght@400;500&display=swap">
<link rel="stylesheet" href="/css/base.css">
<link rel="stylesheet" href="/css/publicacao.css">

<script>
  try {
    var t = localStorage.getItem('tema');
    if (t === 'claro' || t === 'escuro') {
      document.documentElement.dataset.theme = t === 'claro' ? 'light' : 'dark';
    }
  } catch (e) {}
</script>

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "headline": "Não comece a sessão do zero: Codebase Memory MCP",
  "description": "Quatro perguntas sobre um código que o agente não conhece, medidas nas duas rotas: 8 kB pelo grafo, 680 kB lendo arquivo. E uma que o grep não responde.",
  "url": "https://woss.tech/publicacoes/2026-09-10-nao-comece-a-sessao-do-zero.html",
  "mainEntityOfPage": "https://woss.tech/publicacoes/2026-09-10-nao-comece-a-sessao-do-zero.html",
  "datePublished": "2026-09-10",
  "dateModified": "2026-09-10",
  "inLanguage": "pt-BR",
  "articleSection": "Ferramentas",
  "keywords": ["MCP", "agentes", "grafo de código", "tree-sitter", "LLM"],
  "image": "https://woss.tech/assets/og/2026-09-10-nao-comece-a-sessao-do-zero.png",
  "wordCount": 1564,
  "author": {
    "@type": "Person",
    "@id": "https://woss.tech/#autor",
    "name": "Anderson Woss",
    "url": "https://woss.tech/sobre.html"
  },
  "publisher": {
    "@type": "Person",
    "@id": "https://woss.tech/#autor",
    "name": "Anderson Woss"
  },
  "isPartOf": { "@type": "Blog", "@id": "https://woss.tech/#blog" }
}
</script>
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    { "@type": "ListItem", "position": 1, "name": "woss.tech", "item": "https://woss.tech/" },
    { "@type": "ListItem", "position": 2, "name": "Publicações", "item": "https://woss.tech/publicacoes/" },
    { "@type": "ListItem", "position": 3, "name": "Não comece a sessão do zero" }
  ]
}
</script>

<script defer src="https://cdnjs.cloudflare.com/ajax/libs/mermaid/11.15.0/mermaid.min.js"></script>
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/highlight.min.js"></script>
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/languages/bash.min.js"></script>
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/languages/json.min.js"></script>
</head>
<body>

<div class="progress" id="progress" aria-hidden="true"></div>
<a class="skip-link" href="#artigo">Pular para o texto</a>

<header class="nav">
  <div class="nav__inner shell">
    <a class="brand mono" href="/">woss<span class="brand__dot">.</span>tech</a>
    <nav class="nav__links" aria-label="Seções do site">
      <a href="/publicacoes/">Publicações</a>
      <a href="/#topicos">Tópicos</a>
      <a href="/sobre.html">Sobre</a>
      <a href="/feed.xml">RSS</a>
    </nav>
    <button class="theme-toggle mono" type="button" data-theme-toggle aria-live="polite">
      <span class="theme-toggle__icon" aria-hidden="true"></span>
      <span data-theme-label>escuro</span>
    </button>
  </div>
</header>

<header class="post-head">
  <div class="post-head__ascii" id="ascii-stage" aria-hidden="true">
    <pre class="ascii ascii--dim" id="ascii-dim"></pre>
    <pre class="ascii ascii--hot" id="ascii-hot"></pre>
  </div>

  <div class="shell post-head__inner">
    <nav class="post-head__back mono" aria-label="Você está em">
      <a href="/publicacoes/"><span aria-hidden="true">←</span> voltar ao arquivo</a>
    </nav>

    <p class="post-head__meta mono">
      <a class="tag" href="/publicacoes/?topico=Ferramentas">Ferramentas</a>
      <time datetime="2026-09-10">10 set 2026</time>
      <span class="sep">·</span>
      <span data-gerado="diagramas">6 diagramas · 3 gráficos</span>
    </p>

    <h1 class="post-title">Não comece a sessão <em>do zero</em></h1>

    <p class="post-standfirst">
      Quatro perguntas sobre um código que o agente não conhece. Pelo grafo
      elas custam 8 kB. Lendo arquivo, 680 kB — e uma delas não tem resposta.
    </p>
  </div>
</header>

<div class="post-wrap">
  <aside class="toc" id="toc" aria-label="Sumário"></aside>

  <article class="article" id="artigo">

    <p>
      Um agente de IA não tem véspera. Cada sessão nova abre com a mesma
      ignorância da primeira: não sabe onde mora a autenticação, não sabe que
      aquele módulo com nome de utilitário é o coração do domínio, não sabe
      que o arquivo de 6 mil linhas só delega. Para trocar três linhas ele
      precisa <strong>antes</strong> reconstruir o mapa — e reconstruir o mapa
      é <em>grep</em>, ler arquivo inteiro, seguir <em>import</em>, ler outro
      arquivo inteiro. É o que faz um desenvolvedor no primeiro dia, com a
      diferença de que o desenvolvedor faz isso uma vez.
    </p>

    <p>
      O <a href="https://github.com/DeusData/codebase-memory-mcp" rel="noopener">Codebase
      Memory MCP</a> indexa o repositório num grafo de conhecimento em SQLite
      e o expõe por MCP, para que a sessão de amanhã pergunte ao grafo o que a
      de hoje descobriu lendo arquivo. Em vez de descrever a promessa,
      medi.<sup class="ref"><a href="#nota-1" id="ref-1">1</a></sup>
    </p>

    <h2>Quatro perguntas, duas rotas</h2>

    <p>
      Peguei um repositório público que qualquer leitor pode baixar — o
      <code>fastapi/fastapi</code> no <em>commit</em> <code>50113da</code>,
      1.138 arquivos <code>.py</code> e 112.998 linhas — e fiz quatro
      perguntas que aparecem de verdade quando se chega num código
      desconhecido. Cada uma respondida duas vezes: pelo grafo, e pela rota
      que um agente sem grafo é obrigado a seguir.
    </p>

    <div class="table-wrap bleed">
      <table>
        <thead>
          <tr>
            <th>Pergunta</th>
            <th>Pelo grafo</th>
            <th>Lendo arquivo</th>
            <th>Razão</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Onde eu começo?</td>
            <td>3.930 B<br><code>get_architecture</code></td>
            <td>80.459 B<br>README + árvore de <code>.py</code></td>
            <td>20×</td>
          </tr>
          <tr>
            <td>Quem chama isto, e o que ela chama?</td>
            <td>3.528 B<br><code>search_graph</code> + <code>trace_path</code></td>
            <td>303.462 B<br><em>grep</em> + 3 arquivos</td>
            <td>86×</td>
          </tr>
          <tr>
            <td>O que meu <em>diff</em> afeta?</td>
            <td>544 B<br><code>detect_changes</code></td>
            <td>295.629 B<br><code>git diff</code> + 2 arquivos</td>
            <td>543×</td>
          </tr>
          <tr>
            <td>Que função não tem chamador?</td>
            <td>43 B<br><code>query_graph</code></td>
            <td><strong>não responde</strong></td>
            <td>—</td>
          </tr>
        </tbody>
      </table>
    </div>

    <figure class="chart bleed">
      <div class="chart__canvas">
        <svg viewBox="0 0 770 320" role="img"
             aria-label="Gráfico de barras em escala logarítmica comparando os bytes de resposta de quatro perguntas, pelo grafo e lendo arquivo. Onde eu começo: 3.930 bytes contra 80.459. Quem chama isto: 3.528 contra 303.462. O que meu diff afeta: 544 contra 295.629. Que função não tem chamador: 43 bytes pelo grafo e nenhuma resposta pela outra rota.">
          <g class="g-grade">
            <line x1="220" y1="32" x2="220" y2="288"></line>
            <line x1="324" y1="32" x2="324" y2="288"></line>
            <line x1="428" y1="32" x2="428" y2="288"></line>
            <line x1="532" y1="32" x2="532" y2="288"></line>
            <line x1="636" y1="32" x2="636" y2="288"></line>
            <line x1="740" y1="32" x2="740" y2="288"></line>
          </g>
          <g class="g-eixo" text-anchor="middle">
            <text x="220" y="22">10 B</text>
            <text x="324" y="22">100 B</text>
            <text x="428" y="22">1 kB</text>
            <text x="532" y="22">10 kB</text>
            <text x="636" y="22">100 kB</text>
            <text x="740" y="22">1 MB</text>
          </g>

          <text class="g-rotulo" x="206" y="64" text-anchor="end">onde eu começo?</text>
          <rect class="g-barra-grafo"  x="220" y="40" width="270" height="16"></rect>
          <rect class="g-barra-manual" x="220" y="62" width="406" height="16"></rect>
          <text class="g-valor" x="498" y="53">3,9 kB</text>
          <text class="g-valor" x="634" y="75">80 kB</text>

          <text class="g-rotulo" x="206" y="126" text-anchor="end">quem chama isto?</text>
          <rect class="g-barra-grafo"  x="220" y="102" width="265" height="16"></rect>
          <rect class="g-barra-manual" x="220" y="124" width="466" height="16"></rect>
          <text class="g-valor" x="493" y="115">3,5 kB</text>
          <text class="g-valor" x="694" y="137">303 kB</text>

          <text class="g-rotulo" x="206" y="188" text-anchor="end">o que meu diff afeta?</text>
          <rect class="g-barra-grafo"  x="220" y="164" width="181" height="16"></rect>
          <rect class="g-barra-manual" x="220" y="186" width="465" height="16"></rect>
          <text class="g-valor" x="409" y="177">544 B</text>
          <text class="g-valor" x="693" y="199">296 kB</text>

          <text class="g-rotulo" x="206" y="250" text-anchor="end">o que não tem chamador?</text>
          <rect class="g-barra-grafo" x="220" y="226" width="66" height="16"></rect>
          <text class="g-valor" x="294" y="239">43 B</text>
          <text class="g-valor" x="228" y="261">não responde</text>
        </svg>
      </div>
      <ul class="chart__legenda">
        <li data-serie="grafo">pelo grafo</li>
        <li>lendo arquivo</li>
      </ul>
      <figcaption>
        O eixo é <strong>logarítmico</strong>: cada linha da grade vale dez
        vezes a anterior. Numa escala linear as três barras de acento seriam
        invisíveis — o que também seria uma leitura honesta do resultado.
      </figcaption>
    </figure>

    <p>
      Somando as quatro, a rota do grafo devolveu <strong>8.045 bytes</strong>
      e a rota manual <strong>679.550</strong>. Traduzido para a moeda que
      importa numa sessão de agente — contexto — são cerca de 2 mil
      <em>tokens</em> contra 170 mil.<sup class="ref"><a href="#nota-2" id="ref-2">2</a></sup>
    </p>

    <figure class="chart bleed">
      <div class="chart__canvas">
        <svg viewBox="0 0 770 210" role="img"
             aria-label="Gráfico do consumo de uma janela de contexto de 200 mil tokens pelas quatro perguntas: 2.011 tokens pelo grafo, equivalente a 1,0 por cento da janela, contra 169.888 tokens lendo arquivo, equivalente a 84,9 por cento.">
          <text class="g-rotulo" x="70" y="28">pelo grafo — 2.011 tokens, 1,0% da janela</text>
          <rect class="g-trilha"      x="70" y="38" width="670" height="28"></rect>
          <rect class="g-barra-grafo" x="70" y="38" width="7"   height="28"></rect>

          <text class="g-rotulo" x="70" y="98">lendo arquivo — 169.888 tokens, 84,9% da janela</text>
          <rect class="g-trilha"       x="70" y="108" width="670" height="28"></rect>
          <rect class="g-barra-manual" x="70" y="108" width="569" height="28"></rect>

          <g class="g-base">
            <line x1="70" y1="148" x2="740" y2="148"></line>
            <line x1="70" y1="148" x2="70" y2="156"></line>
            <line x1="740" y1="148" x2="740" y2="156"></line>
          </g>
          <text class="g-eixo" x="70" y="174">0</text>
          <text class="g-eixo" x="740" y="174" text-anchor="end">200.000 tokens</text>
          <text class="g-eixo" x="70" y="198">e a quarta pergunta não tem resposta na rota de baixo</text>
        </svg>
      </div>
      <figcaption>
        A mesma sessão, o mesmo trabalho. Embaixo, três perguntas já
        consumiram 85% da janela e não sobrou espaço para <em>fazer</em> a
        mudança — que era o motivo de ter aberto a sessão.
      </figcaption>
    </figure>

    <p>
      E a diferença não é só de volume. O <em>grep</em> devolve
      <strong>posições de texto</strong>; o grafo devolve
      <strong>relações</strong>. São perguntas de tipo diferente, e a quarta
      linha da tabela é a prova: "que função não tem nenhum chamador" não é
      consulta textual, é consulta sobre arestas. Não existe expressão regular
      que responda.
    </p>

    <figure class="diagram bleed">
      <div class="diagram__canvas">
<pre class="mermaid">
flowchart TD
    Q["uma pergunta sobre relação entre símbolos"]
    Q --> G["consulta ao grafo"]
    Q --> R["grep no repositório"]
    G --> GA["devolve as arestas: quem chama, o que chama, a quantos saltos"]
    R --> RA["devolve as posições onde o nome aparece como texto"]
    RA --> RB["abrir cada arquivo e reconstruir a relação lendo"]
    RB --> RC["a relação sai da cabeça do modelo, não do repositório"]
</pre>
      </div>
      <figcaption>
        O nó de baixo é o problema real: relação reconstruída por leitura é
        relação <em>inferida</em>, e inferência sobre código que o modelo
        acabou de conhecer é exatamente onde ele inventa.
      </figcaption>
    </figure>

    <h2>O que cada resposta contém</h2>

    <p>
      Contagem de bytes só interessa se a resposta menor for também a melhor.
      Vale abrir as quatro.
    </p>

    <h3>Onde eu começo?</h3>

    <p>
      Uma chamada, 3.930 bytes, e sai o censo do repositório: quantos nós de
      cada tipo, quantas arestas de cada tipo, as linguagens com a contagem
      real de arquivos, os pacotes e os pontos de entrada.
    </p>

    <figure class="code bleed">
      <div class="code__bar">
        <span class="code__lang mono">bash <span class="code__file">· get_architecture, recortado</span></span>
        <button class="code__copy mono" type="button">copiar</button>
      </div>
<pre><code class="language-bash">total_nodes: 31130
total_edges: 73526

node_labels:                 edge_types:
  Section    15029             DEFINES     36705
  Function    4307             CALLS        7462
  File        2890             USAGE        6457
  Module      2707             SIMILAR_TO   4539
  Route       2574             HANDLES      3888
  Variable    2228             TESTS        3062
  Class        663             IMPORTS      1881
  Method       323             INHERITS      102
  Decorator     15             HTTP_CALLS     47

languages: Python 1138, YAML 42, HTML 5, Bash 5, JavaScript 4, CSS 3, TOML 1
entry_points: 20</code></pre>
      <figcaption>
        Repare em <code>USAGE</code> com 6.457 contra 7.462 de
        <code>CALLS</code>: <strong>46% das referências não têm alvo único
        provado</strong>, e o grafo declara isso em vez de esconder.
        Ferramenta que junta os dois num tipo só de aresta está vendendo
        confiança que não tem.
      </figcaption>
    </figure>

    <h3>Quem chama isto, e o que ela chama?</h3>

    <p>
      A pergunta era sobre <code>solve_dependencies</code>, o miolo da
      injeção de dependência do FastAPI. A primeira chamada acha o símbolo e
      já devolve a faixa de linhas exata, mais o grau de entrada e de saída:
    </p>

    <figure class="code bleed">
      <div class="code__bar">
        <span class="code__lang mono">bash <span class="code__file">· 382 bytes de saída</span></span>
        <button class="code__copy mono" type="button">copiar</button>
      </div>
<pre><code class="language-bash">$ codebase-memory-mcp cli search_graph \
    --project fastapi --name-pattern 'solve_dependencies'

total: 2
fastapi.fastapi.dependencies.utils (fastapi/dependencies/utils.py):
  solve_dependencies Function 586-731 2 20
fastapi.fastapi.routing._FrontendRouteGroup (fastapi/routing.py):
  _solve_dependencies Method 2216-2252 1 7</code></pre>
      <figcaption>
        Antes de ler uma linha eu já sei que a função de 146 linhas em
        <code>utils.py</code> chama vinte coisas e é chamada por duas, e que
        existe um método homônimo em <code>routing.py</code> que não é ela.
      </figcaption>
    </figure>

    <p>
      A segunda chamada percorre o grafo em largura, nas duas direções, e
      devolve em 3.146 bytes os 72 símbolos alcançados até três saltos —
      agrupados por módulo, com a distância de cada um — mais os 3 chamadores.
    </p>

    <figure class="diagram bleed">
      <div class="diagram__canvas">
<pre class="mermaid">
flowchart TD
    E2["handle"] -->|"salto 2"| E1["_solve_dependencies em routing.py"]
    E1 -->|"salto 1"| S["solve_dependencies"]
    S -->|"salto 1"| A["get_dependant, request_body_to_args, _solve_generator e outros 16"]
    A -->|"salto 2"| B["analyze_param, get_typed_signature, get_cached_model_fields e outros 30"]
    B -->|"salto 3"| C["field_annotation_is_scalar, copy_field_info, validate e outros 20"]
</pre>
      </div>
      <figcaption>
        É busca em largura com profundidade limitada, não varredura: os 22
        módulos alcançados saem da travessia de arestas, e o custo não depende
        do tamanho do repositório, mas do raio pedido.
      </figcaption>
    </figure>

    <h3>O que meu <em>diff</em> afeta?</h3>

    <p>
      Aqui a diferença fica mais brutal, e é a pergunta que mais aparece na
      prática: mudei uma linha, o que quebra? Acrescentei um comentário dentro
      de <code>solve_dependencies</code> e chamei <code>detect_changes</code>.
      Ele leu o <em>diff</em> não comitado, mapeou para o símbolo afetado e
      devolveu o raio:
    </p>

    <figure class="code bleed">
      <div class="code__bar">
        <span class="code__lang mono">bash <span class="code__file">· detect_changes, 544 bytes na íntegra</span></span>
        <button class="code__copy mono" type="button">copiar</button>
      </div>
<pre><code class="language-bash">changed_files: 1
  fastapi/dependencies/utils.py
seed_symbols: 1
impacted_total: 3
impacted:
  fastapi.routing._FrontendRouteGroup:
    _solve_dependencies Method 1
    handle              Method 2
  fastapi.routing.py:
    __file__            File 1
impacted_modules:
  fastapi/routing.py 3</code></pre>
      <figcaption>
        Cinco linhas úteis. O <code>git diff</code> equivalente tem 390 bytes
        e diz o que mudou — não diz o que <strong>depende</strong> do que
        mudou, que é a única coisa que eu queria saber.
      </figcaption>
    </figure>

    <figure class="diagram bleed">
      <div class="diagram__canvas">
<pre class="mermaid">
flowchart TD
    D["diff: 1 linha em fastapi/dependencies/utils.py"]
    D --> S["símbolo semente: solve_dependencies"]
    S -->|"salto 1"| A["_solve_dependencies"]
    S -->|"salto 1"| F["o arquivo routing.py"]
    A -->|"salto 2"| B["handle"]
    B --> R(["raio: 3 símbolos, um módulo só"])
</pre>
      </div>
      <figcaption>
        Para chegar nas mesmas três caixas pela outra rota é preciso ler
        <code>utils.py</code> e <code>routing.py</code> inteiros — 295 kB para
        descobrir que o estrago cabe num arquivo.
      </figcaption>
    </figure>

    <h3>Que função não tem chamador?</h3>

    <p>
      Esta é a que muda de categoria. Restrita ao diretório da biblioteca, a
      resposta inteira tem <strong>43 bytes</strong>:
    </p>

    <figure class="code bleed">
      <div class="code__bar">
        <span class="code__lang mono">bash <span class="code__file">· query_graph, openCypher de leitura</span></span>
        <button class="code__copy mono" type="button">copiar</button>
      </div>
<pre><code class="language-bash">MATCH (f:Function)
WHERE f.file_path STARTS WITH 'fastapi/'
  AND NOT EXISTS { (f)&lt;-[:CALLS]-() }
RETURN count(f)

rows: 1  (cols: COUNT(f))
  "10"</code></pre>
      <figcaption>
        10 das 150 funções de <code>fastapi/</code> não têm nenhuma aresta
        <code>CALLS</code> entrando. O que sai do subconjunto suportado —
        escrita, <code>MERGE</code>, <em>list comprehension</em> — falha com
        erro explícito de <code>unsupported</code>, e não devolvendo vazio.
      </figcaption>
    </figure>

    <aside class="callout callout--atencao">
      <p class="callout__label mono" data-marca="[!]">10 não é o número de funções mortas</p>
      <p>
        É o número de <em>candidatas</em>, e a diferença importa. Numa
        biblioteca a API pública é chamada de fora do repositório: sem
        chamador <strong>aqui</strong> não quer dizer sem chamador. Somando-se
        a isso que a consulta olha só <code>CALLS</code> e ignora
        <code>USAGE</code> — as tais 46% de referências sem alvo provado —, o
        grafo serve para <strong>encurtar a lista de suspeitos</strong>, não
        para fechar o caso.
      </p>
    </aside>

    <h2>Por que é barato perguntar</h2>

    <p>
      Vale desfazer uma confusão comum: o Codebase Memory MCP
      <strong>não tem LLM dentro</strong>. Ele é um motor de análise
      estrutural. Quem traduz "quem chama isso?" para
      <code>trace_path(direction="inbound")</code> é o agente que você já está
      usando — e é por isso que não há chave de API nem modelo a configurar.
    </p>

    <figure class="diagram bleed">
      <div class="diagram__canvas">
<pre class="mermaid">
flowchart TD
    V["você pergunta em português"] --> A["o agente escolhe a tool e monta os argumentos"]
    A --> C["o servidor executa a consulta no grafo"]
    C --> S["SQLite devolve as linhas"]
    S --> A2["o agente lê as linhas e escreve a resposta"]
    A2 --> V2["você recebe a cadeia de chamadas em português"]
</pre>
      </div>
      <figcaption>
        Nenhuma caixa deste desenho é um modelo, exceto as duas do agente. O
        servidor é determinístico: a mesma consulta no mesmo grafo dá a mesma
        resposta — o que é a razão de dar para conferir o número.
      </figcaption>
    </figure>

    <p>
      A consulta é barata porque o trabalho difícil já foi feito na indexação,
      em duas passadas. A primeira é <em>tree-sitter</em>, sintática, com as
      gramáticas compiladas dentro do binário. A segunda — que o projeto chama
      de <em>Hybrid LSP</em> — é uma implementação enxuta em C de algoritmos de
      resolução de tipo, e é ela que sabe que
      <code>user.profile.display_name()</code> resolve para
      <code>Profile.display_name</code>, declarado três módulos adiante.
      Existe para Python, TypeScript, PHP, C#, Go, C, C++, Java, Kotlin, Rust
      e Perl; as outras linguagens caem na resolução textual.
    </p>

    <figure class="diagram bleed">
      <div class="diagram__canvas">
<pre class="mermaid">
flowchart TD
    F["arquivos do repositório"] --> D["descoberta: .gitignore, .cbmignore, sem symlink"]
    D --> TS["passada tree-sitter: definições, chamadas e imports"]
    TS --> LSP["passada Hybrid LSP: resolve o alvo por inferência de tipo"]
    LSP --> S["SQLite: nós e arestas, no cache local"]
    S --> Q(["consulta estrutural"])
    S --> A[".codebase-memory/graph.db.zst"]
</pre>
      </div>
      <figcaption>
        A segunda passada é o que separa "há uma chamada com esse nome" de
        "esta chamada resolve para aquela definição" — a diferença entre
        <code>USAGE</code> e <code>CALLS</code> no censo acima.
      </figcaption>
    </figure>

    <p>
      Indexei quatro repositórios públicos de tamanhos bem diferentes, na
      mesma máquina, para ver como esse custo escala:
    </p>

    <div class="table-wrap bleed">
      <table>
        <thead>
          <tr>
            <th>Repositório</th>
            <th>Linhas <code>.py</code></th>
            <th>Indexação</th>
            <th>Nós</th>
            <th>Arestas</th>
            <th>Banco</th>
          </tr>
        </thead>
        <tbody>
          <tr><td><code>psf/requests</code></td><td>12.032</td><td>4,95 s</td><td>1.428</td><td>5.629</td><td>8,6 MB</td></tr>
          <tr><td><code>pallets/flask</code></td><td>18.345</td><td>4,35 s</td><td>2.034</td><td>8.408</td><td>10,2 MB</td></tr>
          <tr><td><code>fastapi/fastapi</code></td><td>112.998</td><td>8,80 s</td><td>31.130</td><td>73.526</td><td>73,9 MB</td></tr>
          <tr><td><code>django/django</code></td><td>526.186</td><td>30,08 s</td><td>55.583</td><td>345.183</td><td>269,8 MB</td></tr>
        </tbody>
      </table>
    </div>

    <figure class="chart bleed">
      <div class="chart__canvas">
        <svg viewBox="0 0 770 300" role="img"
             aria-label="Gráfico de barras da vazão de indexação em linhas por segundo: requests 2.431, flask 4.217, fastapi 12.841 e django 17.492. A vazão cresce com o tamanho do repositório porque o custo fixo de partida domina os repositórios pequenos.">
          <g class="g-grade">
            <line x1="70" y1="194.4" x2="750" y2="194.4"></line>
            <line x1="70" y1="138.9" x2="750" y2="138.9"></line>
            <line x1="70" y1="83.3" x2="750" y2="83.3"></line>
          </g>
          <g class="g-eixo" text-anchor="end">
            <text x="60" y="198">5 mil</text>
            <text x="60" y="143">10 mil</text>
            <text x="60" y="87">15 mil</text>
          </g>

          <rect class="g-barra-grafo" x="105" y="223.0" width="100" height="27.0"></rect>
          <rect class="g-barra-grafo" x="275" y="203.1" width="100" height="46.9"></rect>
          <rect class="g-barra-grafo" x="445" y="107.3" width="100" height="142.7"></rect>
          <rect class="g-barra-grafo" x="615" y="55.6"  width="100" height="194.4"></rect>

          <g class="g-valor" text-anchor="middle">
            <text x="155" y="213">2.431</text>
            <text x="325" y="193">4.217</text>
            <text x="495" y="97">12.841</text>
            <text x="665" y="45">17.492</text>
          </g>

          <g class="g-base">
            <line x1="70" y1="250" x2="750" y2="250"></line>
          </g>

          <g text-anchor="middle">
            <text class="g-rotulo" x="155" y="272">requests</text>
            <text class="g-rotulo" x="325" y="272">flask</text>
            <text class="g-rotulo" x="495" y="272">fastapi</text>
            <text class="g-rotulo" x="665" y="272">django</text>
            <text class="g-eixo" x="155" y="291">12 mil linhas</text>
            <text class="g-eixo" x="325" y="291">18 mil</text>
            <text class="g-eixo" x="495" y="291">113 mil</text>
            <text class="g-eixo" x="665" y="291">526 mil</text>
          </g>
        </svg>
      </div>
      <figcaption>
        Vazão em linhas por segundo. Ela <strong>cresce</strong> com o tamanho
        porque os dois repositórios pequenos gastam a maior parte dos ~4 s
        subindo o processo: abaixo de umas 20 mil linhas você não está medindo
        o indexador, está medindo a partida.
      </figcaption>
    </figure>

    <p>
      Meio milhão de linhas de Python em 30 segundos, uma vez, e depois a
      pergunta sai em milissegundos. O detalhe honesto está numa coluna que
      não coube na tabela: o <code>django</code> teve <strong>51 arquivos com
      trecho que o <em>parser</em> não conseguiu ler</strong> por inteiro
      (<code>parse_partial</code>), contra 3 no <code>flask</code>, 1 no
      <code>requests</code> e nenhum no <code>fastapi</code>. O indexador
      reporta esses arquivos em vez de fingir cobertura — e é por isso que
      afirmação de ausência ainda pede <em>grep</em>.
    </p>

    <h2>As três memórias</h2>

    <p>
      Chamar tudo isso de "memória" esconde que são três coisas com
      durabilidades diferentes. A segunda é a que de fato ensina um agente ao
      seguinte, e é a que quase ninguém usa.
    </p>

    <div class="table-wrap bleed">
      <table>
        <thead>
          <tr><th>Memória</th><th>O que guarda</th><th>Sobrevive a</th></tr>
        </thead>
        <tbody>
          <tr><td>o grafo</td><td>estrutura derivada do código: símbolos, chamadas, rotas</td><td>sessão e reinício da máquina</td></tr>
          <tr><td>o ADR (<code>manage_adr</code>)</td><td>o que o código <strong>não</strong> diz: decisão, <em>trade-off</em>, armadilha</td><td>sessão — e é o único que não se regenera</td></tr>
          <tr><td>o artefato <code>.zst</code></td><td>o grafo comprimido, versionado ao lado do fonte</td><td>a máquina — atravessa o time</td></tr>
        </tbody>
      </table>
    </div>

    <p>
      O grafo é <strong>derivado</strong>: apagar o cache não perde nada além
      de tempo de CPU. O ADR não. Ele é um documento em <em>markdown</em> por
      projeto que um agente escreve e o próximo lê — o recado que quem está
      saindo deixa para quem está chegando:
    </p>

    <figure class="code bleed">
      <div class="code__bar">
        <span class="code__lang mono">markdown <span class="code__file">· o documento que fica gravado</span></span>
        <button class="code__copy mono" type="button">copiar</button>
      </div>
<pre><code>## ARCHITECTURE

A resolução de dependências tem um único ponto de entrada:
solve_dependencies (fastapi/dependencies/utils.py:586-731). O único
chamador real é _FrontendRouteGroup._solve_dependencies
(fastapi/routing.py:2216-2252).

## PATTERNS

Não procure a resolução em routing.py: ela delega.</code></pre>
      <figcaption>
        Isso entra pelo campo <code>content</code> de
        <code>manage_adr(mode='update')</code> e volta inteiro no
        <code>mode='get'</code>. As duas consultas da segunda pergunta viram
        400 bytes que a próxima sessão lê antes de abrir arquivo.
      </figcaption>
    </figure>

    <aside class="callout callout--nota">
      <p class="callout__label mono" data-marca="[i]">o README está à frente do binário</p>
      <p>
        O <code>README</code> do <code>main</code> documenta
        <code>mode='set_sections'</code>, que reescreveria só as seções
        nomeadas. Na <strong>v0.10.8</strong> esse argumento é recusado com
        <code>"the sections argument is not an update primitive and has been
        removed"</code> e <em>nenhuma escrita acontece</em>. Só
        <code>update</code> funciona, e ele <strong>substitui o documento
        inteiro</strong> — leia com <code>get</code> antes de escrever, ou
        você apaga o recado de outra sessão.
      </p>
    </aside>

    <p>
      A terceira memória atravessa pessoas. Indexando com
      <code>persistence</code> ligado, o grafo é exportado para
      <code>.codebase-memory/graph.db.zst</code>, ao lado do fonte: quem clona
      o repositório importa o artefato e roda indexação incremental só do
      próprio <em>diff</em>. No FastAPI o artefato ficou em
      <strong>6,2 MB</strong> contra 73,9 MB de banco local, e o
      <code>artifact.json</code> ao lado registra o <em>commit</em> exato de
      que ele saiu — o que impede alguém de confiar num grafo de três meses
      atrás.
    </p>

    <figure class="diagram bleed">
      <div class="diagram__canvas">
<pre class="mermaid">
sequenceDiagram
    autonumber
    participant A as sessão 1
    participant G as grafo
    participant D as ADR
    participant B as sessão 2

    A->>G: index_repository
    G-->>A: 31.130 nós
    A->>G: trace_path
    A->>D: escreve a conclusão
    Note over D: o que o código não diz
    B->>D: lê antes de tudo
    D-->>B: a conclusão da sessão 1
    B->>G: pergunta só o que falta
</pre>
      </div>
      <figcaption>
        O passo 5 é o ponto do desenho. Sem ele a sessão 2 refaz os passos 1
        a 3 — e o grafo tinha economizado <em>tokens</em>, não conhecimento.
      </figcaption>
    </figure>

    <h2>Instalar e usar</h2>

    <p>
      É um executável nativo único, sem <em>runtime</em> de linguagem, sem
      serviço e sem chave de API. O instalador detecta os agentes já presentes
      na máquina e escreve a configuração de MCP de cada um — na v0.10.8 ele
      declara 43 superfícies de cliente:
    </p>

    <figure class="code bleed">
      <div class="code__bar">
        <span class="code__lang mono">bash <span class="code__file">· macOS / Linux</span></span>
        <button class="code__copy mono" type="button">copiar</button>
      </div>
<pre><code class="language-bash">curl -fsSL https://raw.githubusercontent.com/DeusData/codebase-memory-mcp/main/install.sh | bash

# só o binário, sem mexer na configuração dos agentes:
#   ... | bash -s -- --skip-config</code></pre>
      <figcaption>
        O instalador escreve nos arquivos de configuração dos seus agentes. É
        o que ele deve fazer — e é motivo suficiente para ler o
        <em>script</em> antes de canalizar para o <em>shell</em>.
      </figcaption>
    </figure>

    <p>
      Preferindo configurar à mão, é uma entrada de MCP como qualquer outra.
      No Claude Code, em <code>~/.claude.json</code> ou no
      <code>.mcp.json</code> do projeto:
    </p>

    <figure class="code bleed">
      <div class="code__bar">
        <span class="code__lang mono">json <span class="code__file">· .mcp.json</span></span>
        <button class="code__copy mono" type="button">copiar</button>
      </div>
<pre><code class="language-json">{
  "mcpServers": {
    "codebase-memory-mcp": {
      "command": "/home/voce/.local/bin/codebase-memory-mcp",
      "args": []
    }
  }
}</code></pre>
      <figcaption>
        Caminho absoluto. Com caminho relativo o servidor não sobe e o
        <code>/mcp</code> simplesmente não mostra a entrada.
      </figcaption>
    </figure>

    <p>
      Depois é reiniciar o agente e dizer <em>"indexe este projeto"</em>. Todo
      <em>tool</em> do MCP também é comando de linha, o que serve para depurar
      sem um agente no meio e para pendurar indexação num <em>job</em>
      noturno:
    </p>

    <figure class="code bleed">
      <div class="code__bar">
        <span class="code__lang mono">bash <span class="code__file">· pelo CLI, fora do agente</span></span>
        <button class="code__copy mono" type="button">copiar</button>
      </div>
<pre><code class="language-bash">codebase-memory-mcp cli index_repository --repo-path /caminho/do/repo

codebase-memory-mcp cli search_graph --project meu-projeto \
    --name-pattern '.*Handler.*' --label Function
codebase-memory-mcp cli trace_path --project meu-projeto \
    --function-name solve_dependencies --direction both
codebase-memory-mcp cli detect_changes --project meu-projeto

# o artefato de time NÃO nasce sozinho: persistence é false por default
#   index_repository(repo_path="...", persistence=true)

codebase-memory-mcp config set auto_index true   # indexa ao abrir a sessão
codebase-memory-mcp --ui=true --port=9749        # grafo em 3D no navegador</code></pre>
      <figcaption>
        A ordem que economiza mais é a das quatro perguntas deste texto:
        <code>get_architecture</code> para se orientar,
        <code>search_graph</code> para achar o nome exato,
        <code>trace_path</code> para as relações e
        <code>get_code_snippet</code> só no fim — quando já se sabe quais são
        as 146 linhas que importam.
      </figcaption>
    </figure>

    <h2>O que isso custa</h2>

    <p>
      <strong>Disco.</strong> É o custo mais visível: 31.130 nós ocupam
      73,9 MB, e o <code>django</code> chega a 269,8 MB. Nesta máquina há
      <strong>101 projetos indexados e 5,1 GB de cache</strong>. Tudo
      descartável, nada desprezível.
    </p>

    <p>
      <strong>Frescor.</strong> Um grafo de ontem responde com confiança sobre
      código que mudou hoje, e essa é a falha mais perigosa da ideia toda —
      porque não parece uma falha. O projeto trata com um observador em
      segundo plano, com <code>detect_changes</code> para o que ainda não foi
      comitado e com <code>check_index_coverage</code>, que lista os arquivos
      não cobertos por inteiro. Mas cobertura limpa significa "nenhuma lacuna
      registrada", <strong>não prova de completude</strong>: afirmação de
      ausência continua exigindo <em>grep</em>.
    </p>

    <p>
      <strong>Histórico do Git.</strong> Se você comitar o artefato, comite com
      cadência. Ele é reescrito a cada indexação, o Git guarda cada reescrita
      como um <em>blob</em> novo inteiro, e o próprio projeto documenta um time
      que chegou a ~6 GB em ~350 <em>commits</em> desse único caminho. Um
      marco, uma <em>release</em>, um <em>job</em> noturno — não cada
      salvamento.
    </p>

    <p>
      Feita a conta, ainda fecha com folga. O maior grafo que eu mantenho
      indexado tem 167.902 nós e 765.371 arestas; nenhuma janela de contexto
      comporta aquele repositório, e nunca vai comportar. A pergunta nunca foi
      se o agente cabe no código — é se ele chega na sessão sabendo onde
      procurar. É o mesmo que a gente pede de um desenvolvedor novo: não que
      tenha lido tudo, mas que não comece do zero toda segunda-feira.
    </p>

    <hr>

    <section class="footnotes">
      <p class="callout__label mono" data-marca="[†]">notas</p>
      <ol>
        <li id="nota-1">
          Versão medida: <code>codebase-memory-mcp 0.10.8</code>, MIT, em
          Ubuntu 24.04.5 LTS com Intel Core i7-1355U (12 <em>threads</em>) e
          31 GiB de RAM. Repositórios clonados com <code>--depth 1</code> nos
          <em>commits</em> <code>50113da</code> (fastapi),
          <code>2b30f62</code> (django), <code>d73fa1c</code> (flask) e
          <code>dae7ef6</code> (requests). Tempo de indexação por
          <code>/usr/bin/time -f %e</code>; tamanho de banco e de artefato em
          MB decimais, por <code>stat -c%s</code>. Os números de outras
          máquinas citados no texto — o kernel do Linux em 3 minutos, os ~6 GB
          de histórico — são do <code>README</code> do projeto e da
          <a href="https://arxiv.org/abs/2603.27277" rel="noopener"><em>preprint</em>
          arXiv:2603.27277</a>; não são meus.
          <a class="volta" href="#ref-1" aria-label="Voltar ao texto">↩</a>
        </li>
        <li id="nota-2">
          As quatro medições, para reprodução. <strong>Onde eu começo</strong>:
          <code>cli get_architecture</code> (3.930 B) contra
          <code>wc -c README.md</code> (22.780 B) mais a listagem de
          <code>find . -name '*.py'</code> (57.679 B).
          <strong>Quem chama isto</strong>: <code>cli search_graph
          --name-pattern 'solve_dependencies'</code> (382 B) e <code>cli
          trace_path --direction both --depth 3</code> (3.146 B) contra
          <code>grep -rn "solve_dependencies" --include='*.py' .</code>
          (558 B, 8 ocorrências) mais <code>wc -c</code> de
          <code>fastapi/dependencies/utils.py</code>,
          <code>fastapi/routing.py</code> e
          <code>fastapi/dependencies/models.py</code> (302.904 B).
          <strong>O que meu diff afeta</strong>: <code>cli
          detect_changes</code> (544 B) contra <code>git diff</code> (390 B)
          mais os dois arquivos do raio (295.239 B).
          <strong>Sem chamador</strong>: o <code>query_graph</code> do texto
          (43 B). Comparei <strong>bytes de saída</strong>, não
          <em>tokens</em> contados com um <em>tokenizer</em>: a conversão de
          4 bytes por <em>token</em> é a mesma razão que a ferramenta usa como
          teto ao dimensionar resposta, e serve para ordem de grandeza, não
          para dois dígitos de precisão. A janela de 200 mil é a referência do
          gráfico, não um limite do servidor. O nome do projeto nos blocos
          está encurtado para <code>fastapi</code>: o derivado do caminho aqui
          era mais longo, e só o nome muda.
          <a class="volta" href="#ref-2" aria-label="Voltar ao texto">↩</a>
        </li>
      </ol>
    </section>

  </article>
</div>

<section class="post-end">
  <div class="shell post-end__grid">
    <div class="autor">
      <div class="autor__selo mono" aria-hidden="true">AW</div>
      <div>
        <p class="autor__nome">Anderson Woss</p>
        <p>
          Engenheiro de software. Escrevo aqui sobre sistemas distribuídos que
          precisam continuar de pé e modelos que precisam parar de inventar.
        </p>
        <ul class="autor__links">
          <li><a href="https://github.com/acwoss" rel="me noopener">github</a></li>
          <li><a href="https://linkedin.com/in/woss" rel="me noopener">linkedin</a></li>
          <li><a href="mailto:anderson@woss.tech">anderson@woss.tech</a></li>
        </ul>
      </div>
    </div>

    <nav class="vizinhos" aria-label="Outras publicações">
      <a class="vizinho" href="/publicacoes/">
        <span class="vizinho__dir mono">arquivo →</span>
        <span class="vizinho__titulo">Ver todas as publicações</span>
      </a>
      <a class="vizinho" href="/feed.xml">
        <span class="vizinho__dir mono">rss →</span>
        <span class="vizinho__titulo">Assinar o feed</span>
      </a>
    </nav>
  </div>
</section>

<footer class="footer">
  <div class="shell footer__inner">
    <p class="mono">© 2026 Anderson Woss · woss.tech — escrito à mão, sem CMS.</p>
    <p class="mono footer__note">
      publicado em 10 set 2026 · <a href="https://github.com/acwoss/woss.tech" rel="noopener">código do site</a>
    </p>
  </div>
</footer>

<script defer src="/js/site.js"></script>
<script defer src="/js/ascii.js"></script>
<script defer src="/js/publicacao.js"></script>
<script>
  window.addEventListener('load', function () {
    if (window.hljs) window.hljs.highlightAll();
  });
</script>
</body>
</html>
